name: faya_clinic
description: A new Flutter project.

publish_to: "none"

version: 1.0.7+18

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  badges: ^2.0.3
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  chat_bubbles: ^1.3.1
  cloud_firestore: ^3.2.1
  collection: ^1.15.0-nullsafety.4
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.5
  easy_localization: ^3.0.1
  email_validator: ^2.0.1
  firebase_analytics: ^9.1.12
  firebase_app_check: ^0.0.6+18
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  firebase_database: ^9.1.0
  firebase_messaging: ^11.4.4
  firebase_storage: ^10.3.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.6.1
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^1.1.1+1
  flutter_typeahead: ^4.0.0
  google_maps_flutter: ^2.1.8
  hive: ^2.2.3
  http: ^0.13.4
  image_picker: ^0.8.5+3
  image_picker_for_web: ^2.1.8
  intro_slider: ^3.0.9
  month_year_picker: ^0.2.0+1
  package_info: ^2.0.2
  path: ^1.8.1
  path_provider: ^2.0.11
  percent_indicator: ^4.2.2
  provider: ^6.0.3
  syncfusion_flutter_datepicker: ^20.2.36
  tab_indicator_styler: ^2.0.0
  toast: ^0.3.0
  url_launcher: ^6.1.4
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/languages/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal_Regular.ttf
        - asset: assets/fonts/Tajawal/Tajawal_Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal/Tajawal_ExtraBold.ttf
          weight: 900
          # style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
