name: faya_clinic
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  badges: ^2.0.2
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  chat_bubbles: ^1.2.0
  cloud_firestore: ^3.1.13
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  email_validator: ^2.0.1
  firebase_analytics: ^9.1.6
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  firebase_messaging: ^11.2.14
  firebase_storage: ^10.2.16
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.4.1
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^1.0.3
  flutter_typeahead: ^3.2.1
  google_maps_flutter: ^2.1.1
  hive: ^2.0.5
  http: ^0.13.4
  image_picker: ^0.8.5+3
  image_picker_for_web: ^2.1.8
  intro_slider: ^3.0.2
  month_year_picker: ^0.1.0+1
  package_info: ^2.0.2
  path: ^1.8.0
  path_provider: ^2.0.8
  percent_indicator: ^4.0.0
  provider: ^6.0.1
  syncfusion_flutter_datepicker: ^20.1.51
  tab_indicator_styler: ^2.0.0
  toast: ^0.3.0
  url_launcher: ^6.0.17
  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/languages/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal_Regular.ttf
        - asset: assets/fonts/Tajawal/Tajawal_Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal/Tajawal_ExtraBold.ttf
          weight: 900
          # style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
